### ISSUE TITLE
Implement schema + document models (Django ORM) and hook it to API

### ISSUE THREAD

**Issue by Jemoka** [scalander/scalander#4]
Note that you should be doing...

- Implement the data models
- Register the "app" where the models are with `settings.py`
- Register the app with the admin panel
- Create an admin password and share the DB?
- Actually create the API routes in #2 through new views

Here's a tutorial: https://docs.djangoproject.com/en/4.1/intro/tutorial02/, which I think includes everything.

**Comment by thegail** [comment]
- [ ] Plan necessary API routes (.5 hr)
- [ ] Write API logic (.5 hr each x 4-ish)
- [ ] Create API routes/views (1 hr)

Total for this task: 3.5 hr

**Comment by Jemoka** [comment]
branch? + PR?

**Comment by thegail** [comment]
Closed by #19
