### ISSUE TITLE
Sending emails

### ISSUE THREAD

**Issue by Jemoka** [scalander/scalander#5]
Create some kind of API to send emails. This is actually needed for MVP because our user is particularly frustrated by the need to manually chase people down.

**Comment by Papayapaya** [comment]
-automate sending emails (4 hrs)
-incorporate link, write email (30 min)

**Comment by Jm0rr** [comment]
figure out how to send emails (2hrs)
send emails (1.5 hrs)
hook up with other code (.5 hrs)
