### ISSUE TITLE
google calendar API APIng

### ISSUE THREAD

**Issue by Jemoka** [scalander/scalander#9]
Good to figure out how to connect with #3. In and outgress.

**Comment by Jemoka** [comment]
Closed #8, this issue now represents both google calendar => our availablity schema (ingress) AND our schema => google calendar (outgress)

**Comment by Papayapaya** [comment]
- [x] test, edit, and fix get_freebusy (2 hr)
- [ ] create an id for the ics to append to a url (.5 hr)
- [ ] create a url with the id (2 hr)

total: 4.5 hours

**Comment by Papayapaya** [comment]
https://github.com/scalander/scalander/pull/18
